/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef commandCenter_CONSTANTS_H
#define commandCenter_CONSTANTS_H

#include "commandCenter_types.h"



class commandCenterConstants {
 public:
  commandCenterConstants();

};

extern const commandCenterConstants g_commandCenter_constants;



#endif
