/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef commandCenter_TYPES_H
#define commandCenter_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




struct Request_Type {
  enum type {
    VC = 1,
    VQ = 2,
    VIQ = 3
  };
};

extern const std::map<int, const char*> _Request_Type_VALUES_TO_NAMES;

struct Service_Type {
  enum type {
    ASR = 1,
    IMM = 2,
    QA = 3
  };
};

extern const std::map<int, const char*> _Service_Type_VALUES_TO_NAMES;



#endif
