/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "commandCenter_constants.h"



const commandCenterConstants g_commandCenter_constants;

commandCenterConstants::commandCenterConstants() {
}



