//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./hello_types');
//HELPER FUNCTIONS AND STRUCTURES

HelloSvc_hello_func_args = function(args) {
};
HelloSvc_hello_func_args.prototype = {};
HelloSvc_hello_func_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloSvc_hello_func_args.prototype.write = function(output) {
  output.writeStructBegin('HelloSvc_hello_func_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HelloSvc_hello_func_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
HelloSvc_hello_func_result.prototype = {};
HelloSvc_hello_func_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloSvc_hello_func_result.prototype.write = function(output) {
  output.writeStructBegin('HelloSvc_hello_func_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HelloSvc_send_file_args = function(args) {
  this.data = null;
  if (args) {
    if (args.data !== undefined) {
      this.data = args.data;
    }
  }
};
HelloSvc_send_file_args.prototype = {};
HelloSvc_send_file_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.data = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloSvc_send_file_args.prototype.write = function(output) {
  output.writeStructBegin('HelloSvc_send_file_args');
  if (this.data !== null && this.data !== undefined) {
    output.writeFieldBegin('data', Thrift.Type.STRING, 1);
    output.writeString(this.data);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HelloSvc_send_file_result = function(args) {
};
HelloSvc_send_file_result.prototype = {};
HelloSvc_send_file_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloSvc_send_file_result.prototype.write = function(output) {
  output.writeStructBegin('HelloSvc_send_file_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HelloSvcClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
HelloSvcClient.prototype = {};
HelloSvcClient.prototype.seqid = function() { return this._seqid; }
HelloSvcClient.prototype.new_seqid = function() { return this._seqid += 1; }
HelloSvcClient.prototype.hello_func = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_hello_func();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_hello_func();
  }
};

HelloSvcClient.prototype.send_hello_func = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('hello_func', Thrift.MessageType.CALL, this.seqid());
  var args = new HelloSvc_hello_func_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HelloSvcClient.prototype.recv_hello_func = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HelloSvc_hello_func_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('hello_func failed: unknown result');
};
HelloSvcClient.prototype.send_file = function(data, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_send_file(data);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_send_file(data);
  }
};

HelloSvcClient.prototype.send_send_file = function(data) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('send_file', Thrift.MessageType.CALL, this.seqid());
  var args = new HelloSvc_send_file_args();
  args.data = data;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HelloSvcClient.prototype.recv_send_file = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HelloSvc_send_file_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
HelloSvcProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
HelloSvcProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

HelloSvcProcessor.prototype.process_hello_func = function(seqid, input, output) {
  var args = new HelloSvc_hello_func_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.hello_func.length === 0) {
    Q.fcall(this._handler.hello_func)
      .then(function(result) {
        var result = new HelloSvc_hello_func_result({success: result});
        output.writeMessageBegin("hello_func", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("hello_func", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.hello_func(function (err, result) {
      if (err == null) {
        var result = new HelloSvc_hello_func_result((err != null ? err : {success: result}));
        output.writeMessageBegin("hello_func", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("hello_func", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

HelloSvcProcessor.prototype.process_send_file = function(seqid, input, output) {
  var args = new HelloSvc_send_file_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.send_file.length === 1) {
    Q.fcall(this._handler.send_file, args.data)
      .then(function(result) {
        var result = new HelloSvc_send_file_result({success: result});
        output.writeMessageBegin("send_file", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("send_file", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.send_file(args.data, function (err, result) {
      if (err == null) {
        var result = new HelloSvc_send_file_result((err != null ? err : {success: result}));
        output.writeMessageBegin("send_file", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("send_file", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

