/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SennaService_CONSTANTS_H
#define SennaService_CONSTANTS_H

#include "SennaService_types.h"



class SennaServiceConstants {
 public:
  SennaServiceConstants();

};

extern const SennaServiceConstants g_SennaService_constants;



#endif
