/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SennaService_constants.h"



const SennaServiceConstants g_SennaService_constants;

SennaServiceConstants::SennaServiceConstants() {
}



