// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.


#include <stdio.h>
#include <iostream>
#include <sys/types.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <string>
#include <fstream>
#include <sstream>

#include "KaldiService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace std;
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

void readFromPipe(int,string&);


class KaldiServiceHandler : virtual public KaldiServiceIf {
 public:
  KaldiServiceHandler() {
    // Your initialization goes here
  	
	}
  void kaldi_asr(std::string& _return, const std::string& audio_file) {
    // Your implementation goes here
	std::cout << "Decoding audio file...." <<std::endl;
	//Still need to implement the decoding of the file
	std::string audio_path = "inputserver.wav";
	ofstream audiofile(audio_path.c_str(), ios::binary);
	audiofile.write(audio_file.c_str(),audio_file.size());
	audiofile.close();
	string kotae;
	
	pid_t pid;
	int fds[2];
	int fds2[2];	
	
	pipe (fds);
	pipe (fds2);
	pid=fork();
	
	if(pid ==0){  	
		close (fds[1]);
		close (fds2[0]);
	 	dup2(fds[0],STDIN_FILENO);
		dup2(fds2[1],STDOUT_FILENO);	
	 	execl("../../../src/online2bin/online2-wav-nnet2-latgen-faster",
					"--do-endpointing=false",
					"--online=true",
					"--config=../../nnet_a_gpu_online/conf/online_nnet2_decoding.conf",
					"--max-active=7000",
					"--beam=15.0",
					"--lattice-beam=6.0",
					"--acoustic-scale=0.1",
					"--word-symbol-table=../../graph/words.txt",
					"../../nnet_a_gpu_online/smbr_epoch2.mdl", 
					"../../graph/HCLG.fst",
					"\"ark:echo utterance-id1 utterance-id1|\"",
					"\"scp:echo utterance-id1 null|\"",
					"ark:/dev/null",(char*)NULL);

		}
		else if(pid <0){
			perror("fork");
		}
		else {
			FILE * stream;
			close (fds[0]);
			close (fds2[1]);
			stream = fdopen (fds[1],"w");
			fprintf (stream, "inputserver.wav");
			fflush(stream);
			close(fds[1]);
			readFromPipe(fds2[0],kotae);
		}	
		_return = kotae;
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<KaldiServiceHandler> handler(new KaldiServiceHandler());
  shared_ptr<TProcessor> processor(new KaldiServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}
void readFromPipe( int fd, string& kotae )
{
    FILE *stream;
    int ch;
		char buffer[4096];
    if ( (stream = fdopen( fd, "r" )) == NULL )
    {
        perror( "fdopen() r" );
    }
    while ( fgets (buffer, sizeof (buffer), stream) != NULL )
				kotae =buffer;
    fflush( stream );
}
