/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kaldi_constants.h"



const kaldiConstants g_kaldi_constants;

kaldiConstants::kaldiConstants() {
}



