/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kaldi_CONSTANTS_H
#define kaldi_CONSTANTS_H

#include "kaldi_types.h"



class kaldiConstants {
 public:
  kaldiConstants();

};

extern const kaldiConstants g_kaldi_constants;



#endif
