/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "commandCenter_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>



int _kRequest_TypeValues[] = {
  Request_Type::VC,
  Request_Type::VQ,
  Request_Type::VIQ
};
const char* _kRequest_TypeNames[] = {
  "VC",
  "VQ",
  "VIQ"
};
const std::map<int, const char*> _Request_Type_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kRequest_TypeValues, _kRequest_TypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kService_TypeValues[] = {
  Service_Type::ASR,
  Service_Type::IMM,
  Service_Type::QA
};
const char* _kService_TypeNames[] = {
  "ASR",
  "IMM",
  "QA"
};
const std::map<int, const char*> _Service_Type_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kService_TypeValues, _kService_TypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


