/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef qaservice_CONSTANTS_H
#define qaservice_CONSTANTS_H

#include "qaservice_types.h"

namespace qastubs {

class qaserviceConstants {
 public:
  qaserviceConstants();

};

extern const qaserviceConstants g_qaservice_constants;

} // namespace

#endif
