// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "QAService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::qastubs;

class QAServiceHandler : virtual public QAServiceIf {
 public:
  QAServiceHandler() {
    // Your initialization goes here
  }

  void askQuestion(const std::vector<std::string> & arguments) {
    // Your implementation goes here
    printf("askQuestion\n");
  }

  void askFactoidThrift(std::string& _return, const std::string& question) {
    // Your implementation goes here
    printf("askFactoidThrift\n");
  }

  void askFactoidThriftDebug(std::string& _return, const std::string& question) {
    // Your implementation goes here
    printf("askFactoidThriftDebug\n");
  }

  void askListThrift(std::vector<std::string> & _return, const std::string& question) {
    // Your implementation goes here
    printf("askListThrift\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<QAServiceHandler> handler(new QAServiceHandler());
  shared_ptr<TProcessor> processor(new QAServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

