/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "qaservice_constants.h"

namespace qastubs {

const qaserviceConstants g_qaservice_constants;

qaserviceConstants::qaserviceConstants() {
}

} // namespace

